/** A guided course: an ordered path of concepts, each building on the previous ones. */
export interface Course {
  id: string;
  title: string;
  description: string;
  /** Ionicons name. */
  icon: string;
  /** Built into the app (static) or generated by the AI and stored on the device. */
  builtIn: boolean;
  concepts: CourseConcept[];
  created_at?: string;
}

export interface CourseConcept {
  /** Stable within the course, used to link library concepts back to their station. */
  key: string;
  title: string;
  /** One line shown on the map. */
  summary: string;
  /** The lesson: a plain-language explanation. Paragraphs separated by blank lines. */
  explanation: string;
  cards: { question: string; answer: string }[];
}
