/** The four levels every course climbs through, from the basics to master's-degree depth. */
export const LEVEL_KEYS = ['foundations', 'advanced', 'bachelor', 'master'] as const;
export type LevelKey = (typeof LEVEL_KEYS)[number];

/** A guided course: levels of ordered stations, each building on the ones before it. */
export interface Course {
  id: string;
  title: string;
  description: string;
  /** Ionicons name. */
  icon: string;
  /** Built into the app (static) or generated by the AI and stored on the device. */
  builtIn: boolean;
  levels: CourseLevel[];
  created_at?: string;
}

export interface CourseLevel {
  key: LevelKey;
  stations: CourseConcept[];
  /** Placement questions: answering most correctly means this level is already known. */
  quiz: QuizQuestion[];
}

export interface CourseConcept {
  /** Unique within the course; links library concepts back to their station. */
  key: string;
  title: string;
  /** One line shown on the map. */
  summary: string;
  /**
   * The lesson (paragraphs separated by blank lines) and its flashcards.
   * Built-in foundations ship with them; higher stations get them from the AI
   * the first time they're opened, and they're then saved on the device.
   */
  explanation?: string;
  cards?: { question: string; answer: string }[];
}

export interface QuizQuestion {
  question: string;
  options: string[];
  /** Index into options. */
  correct: number;
}

export interface StationRef {
  station: CourseConcept;
  level: CourseLevel;
  levelIndex: number;
  /** Position in the whole course (0-based). */
  index: number;
}

/** All stations in course order, with the level each belongs to. */
export function stationsOf(course: Course): StationRef[] {
  const out: StationRef[] = [];
  course.levels.forEach((level, levelIndex) => {
    for (const station of level.stations) out.push({ station, level, levelIndex, index: out.length });
  });
  return out;
}

export const findStation = (course: Course, key: string) => stationsOf(course).find((s) => s.station.key === key);

/** Courses saved before levels existed had a flat `concepts` list; treat it as the foundations. */
export function normalizeCourse(raw: Course | (Omit<Course, 'levels'> & { concepts: CourseConcept[] })): Course {
  if ('levels' in raw && Array.isArray(raw.levels)) return raw;
  const { concepts, ...rest } = raw as Omit<Course, 'levels'> & { concepts: CourseConcept[] };
  return { ...rest, levels: [{ key: 'foundations', stations: concepts ?? [], quiz: [] }] };
}
